import { Eyebrow, Reveal, Section } from "./primitives";
import influencer from "@/assets/influencer.jpg";

const stats = [
  {
    figure: "+60%",
    body: "More high-quality views reported by Google for virtual try-on imagery compared with other shopping images.",
    source: "Source: Google Shopping virtual try-on announcement",
    href: "https://blog.google/products/shopping/virtual-try-on-google-generative-ai/",
  },
  {
    figure: "65%",
    body: "Rebecca Minkoff shoppers who viewed a product in AR were reported by Shopify as more likely to purchase.",
    source: "Source: Shopify AR commerce case study",
    href: "https://www.shopify.com/blog/ar-shopping",
  },
  {
    figure: "55%",
    body: "of online apparel shoppers surveyed by Google/Ipsos said they had returned an item because it looked different on them than expected.",
    source: "Source: Google / Ipsos apparel shopper survey",
    href: "https://blog.google/products/shopping/virtual-try-on-google-generative-ai/",
  },
];

export function WhyItMatters() {
  return (
    <Section id="evidence" tone="ink">
      <Reveal>
        <p className="eyebrow text-ink-foreground/50">Why this matters</p>
        <h2 className="display-lg mt-6">Attention before transaction.</h2>
      </Reveal>

      <div className="mt-16 grid gap-6 md:grid-cols-3">
        {stats.map((s, i) => (
          <Reveal key={s.figure} delay={i * 110} className="border border-ink-foreground/15 p-8">
            <p className="font-display text-6xl font-extrabold tracking-tight text-electric">
              {s.figure}
            </p>
            <p className="mt-6 text-sm leading-relaxed text-ink-foreground/75">{s.body}</p>
            <a
              href={s.href}
              target="_blank"
              rel="noreferrer noopener"
              className="mt-6 inline-block text-[0.6rem] font-semibold uppercase tracking-[0.18em] text-ink-foreground/45 underline decoration-ink-foreground/25 underline-offset-4 hover:text-ink-foreground"
            >
              {s.source}
            </a>
          </Reveal>
        ))}
      </div>

      <Reveal delay={120}>
        <p className="mt-14 max-w-3xl text-sm leading-relaxed text-ink-foreground/60">
          Virtual try-on and immersive commerce can increase engagement and buying confidence. The
          figures above are external industry evidence published by third parties — they are not
          results generated by our company and are not a promise of performance for your store.
        </p>
      </Reveal>
    </Section>
  );
}

const loop = ["See", "Try", "Create", "Share", "Buy", "Return"];

export function EngagementLoop() {
  return (
    <Section tone="paper">
      <div className="grid gap-16 lg:grid-cols-[1fr_1fr] lg:items-center">
        <div>
          <Reveal>
            <Eyebrow>The engagement loop</Eyebrow>
            <h2 className="display-lg mt-6">Turn shopping into play.</h2>
          </Reveal>
          <Reveal delay={120}>
            <p className="mt-8 max-w-lg text-lg leading-relaxed text-muted-foreground">
              The longer customers interact with your products, the more opportunities your brand has
              to create desire, collect intent signals and generate a purchase.
            </p>
          </Reveal>
        </div>

        <Reveal delay={150} className="relative mx-auto aspect-square w-full max-w-[420px]">
          <div className="spin-slow absolute inset-0 rounded-full border border-dashed border-border" />
          <div className="absolute inset-[18%] rounded-full border border-border" />
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center">
              <p className="eyebrow">Your brand</p>
              <p className="display-md mt-2">Atelier</p>
            </div>
          </div>
          {loop.map((step, i) => {
            const angle = (i / loop.length) * Math.PI * 2 - Math.PI / 2;
            return (
              <span
                key={step}
                className="absolute flex h-20 w-20 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-border bg-card text-[0.65rem] font-semibold uppercase tracking-[0.16em] shadow-card"
                style={{
                  left: `${50 + 44 * Math.cos(angle)}%`,
                  top: `${50 + 44 * Math.sin(angle)}%`,
                }}
              >
                {step}
              </span>
            );
          })}
        </Reveal>
      </div>
    </Section>
  );
}

const viral = [
  "Influencer wears product",
  "Customer tries product",
  "Customer creates photo with influencer",
  "Customer shares photo",
  "Friend opens experience",
  "New customer",
];

export function InfluencerCommerce() {
  return (
    <section className="relative isolate overflow-hidden bg-ink text-ink-foreground">
      <img
        src={influencer}
        alt="Brand ambassador editorial photograph"
        loading="lazy"
        width={1408}
        height={1024}
        className="absolute inset-0 h-full w-full object-cover opacity-40"
      />
      <div className="relative mx-auto w-full max-w-[1280px] px-5 py-32 sm:px-8 md:py-40">
        <Reveal>
          <p className="eyebrow text-ink-foreground/60">Influencer commerce</p>
          <h2 className="display-lg mt-6 max-w-4xl">Already working with an influencer?</h2>
          <h3 className="display-md mt-4 max-w-3xl text-ink-foreground/75">
            Make them part of the store experience.
          </h3>
        </Reveal>
        <Reveal delay={120}>
          <p className="mt-8 max-w-2xl text-lg leading-relaxed text-ink-foreground/75">
            Instead of customers simply seeing an influencer wearing your products, let them create
            experiences around that influencer.
          </p>
        </Reveal>

        <div className="mt-14 grid gap-3 md:grid-cols-3">
          {viral.map((v, i) => (
            <Reveal
              key={v}
              delay={i * 90}
              className="flex items-start gap-4 border border-ink-foreground/20 bg-ink/40 p-6 backdrop-blur-sm"
            >
              <span className="font-display text-sm text-electric">0{i + 1}</span>
              <span className="text-sm font-semibold uppercase tracking-[0.12em]">{v}</span>
            </Reveal>
          ))}
        </div>

        <Reveal delay={120}>
          <p className="mt-10 max-w-2xl text-[0.7rem] leading-relaxed text-ink-foreground/50">
            Experiences featuring a named person require the appropriate image and likeness rights.
            The brand is responsible for obtaining written permission before uploading influencer or
            ambassador assets.
          </p>
        </Reveal>
      </div>
    </section>
  );
}
