import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import heroModel from "@/assets/hero-model.jpg";
import sceneCity from "@/assets/scene-city.jpg";
import productPolo from "@/assets/product-polo.jpg";

const products = ["Polo", "Jacket", "Dress", "Trousers"];

const actions = [
  "Try on",
  "Complete my look",
  "Create a photo",
  "With our influencer",
  "Animate",
  "Share",
];

export function PhoneDemo({ className }: { className?: string }) {
  const [product, setProduct] = useState(0);
  const [stage, setStage] = useState<"idle" | "processing" | "done">("idle");

  useEffect(() => {
    if (stage !== "processing") return;
    const t = setTimeout(() => setStage("done"), 1900);
    return () => clearTimeout(t);
  }, [stage]);

  return (
    <div className={cn("relative", className)}>
      {/* floating notification */}
      <div
        className={cn(
          "absolute -left-4 top-10 z-20 flex items-center gap-2 border border-border bg-card px-4 py-3 shadow-float transition-all duration-700 sm:-left-10",
          stage === "done" ? "translate-y-0 opacity-100" : "pointer-events-none translate-y-3 opacity-0",
        )}
      >
        <span className="text-electric">✨</span>
        <span className="text-[0.65rem] font-semibold uppercase tracking-[0.18em]">
          Your look is ready
        </span>
      </div>

      {/* floating shopify handoff */}
      <div className="absolute -right-2 bottom-24 z-20 hidden border border-border bg-card px-4 py-3 shadow-float float-slow sm:block">
        <p className="text-[0.6rem] font-semibold uppercase tracking-[0.2em] text-muted-foreground">
          Buy
        </p>
        <p className="mt-1 text-[0.7rem] font-semibold uppercase tracking-[0.12em]">
          Shopify checkout →
        </p>
      </div>

      <div className="mx-auto w-full max-w-[340px] rounded-[2.6rem] border border-foreground/15 bg-foreground/5 p-3 shadow-float">
        <div className="overflow-hidden rounded-[2.1rem] bg-card">
          {/* status bar */}
          <div className="flex items-center justify-between px-5 pt-4 text-[0.6rem] font-semibold uppercase tracking-[0.2em] text-muted-foreground">
            <span>9:41</span>
            <span>The Studio</span>
          </div>

          {/* canvas */}
          <div className="relative mt-3 aspect-[3/4] overflow-hidden bg-muted">
            <img
              src={heroModel}
              alt="Shopper photo before virtual try-on"
              width={1024}
              height={1408}
              className={cn(
                "absolute inset-0 h-full w-full object-cover transition-all duration-1000",
                stage === "done" ? "scale-105 opacity-0" : "opacity-100",
              )}
            />
            <img
              src={sceneCity}
              alt="Shopper wearing the garment generated by AI"
              loading="lazy"
              width={1024}
              height={1280}
              className={cn(
                "absolute inset-0 h-full w-full object-cover transition-all duration-1000",
                stage === "done" ? "opacity-100" : "opacity-0",
              )}
            />
            {stage === "processing" && (
              <div className="absolute inset-0 shimmer-sweep bg-foreground/10" />
            )}
            <div className="absolute left-3 top-3 border border-card/70 bg-foreground/60 px-2 py-1 text-[0.55rem] font-semibold uppercase tracking-[0.2em] text-primary-foreground">
              {stage === "idle" ? "Your photo" : stage === "processing" ? "Generating" : "Your look"}
            </div>
          </div>

          {/* carousel */}
          <div className="flex gap-2 overflow-x-auto px-3 py-3">
            {products.map((p, i) => (
              <button
                key={p}
                type="button"
                onClick={() => {
                  setProduct(i);
                  setStage("idle");
                }}
                className={cn(
                  "flex w-[72px] shrink-0 flex-col items-center gap-1 border p-1 transition-colors",
                  i === product ? "border-foreground" : "border-border hover:border-foreground/40",
                )}
              >
                <img
                  src={productPolo}
                  alt={p}
                  loading="lazy"
                  width={912}
                  height={1104}
                  className="h-14 w-full object-cover"
                />
                <span className="text-[0.55rem] font-semibold uppercase tracking-[0.14em]">{p}</span>
              </button>
            ))}
          </div>

          {/* primary action */}
          <div className="px-3 pb-3">
            <button
              type="button"
              onClick={() => setStage(stage === "done" ? "idle" : "processing")}
              className="w-full bg-electric px-4 py-3 text-[0.65rem] font-semibold uppercase tracking-[0.2em] text-electric-foreground transition-all hover:brightness-110"
            >
              {stage === "idle" ? "Try it on" : stage === "processing" ? "Generating…" : "Try another"}
            </button>
          </div>

          {/* action pills */}
          <div className="flex flex-wrap gap-1.5 border-t border-border px-3 py-3">
            {actions.map((a, i) => (
              <span
                key={a}
                className={cn(
                  "border border-border px-2.5 py-1.5 text-[0.55rem] font-semibold uppercase tracking-[0.14em] transition-all duration-500",
                  stage === "done"
                    ? "translate-y-0 border-foreground/30 opacity-100"
                    : "translate-y-1 opacity-45",
                )}
                style={{ transitionDelay: `${i * 70}ms` }}
              >
                {a}
              </span>
            ))}
            <span className="bg-foreground px-2.5 py-1.5 text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-primary-foreground">
              Buy
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
